### ISSUE TITLE
Counter not counting

### ISSUE THREAD

**Issue by surajkadapa** [surajkadapa/3_bit_up#1]
The counter is not counting up and the clock is not working as it is meant to, make sure it does.

**Comment by IshaanNene** [comment]
I want to be assgined

**Comment by surajkadapa** [comment]
@IshaanNene Yes. The time limit is 1 hour. If not, others can ask to be assigned.

**Comment by surajkadapa** [comment]
@IshaanNene Yes. The time limit is 1 hour. If not, others can ask to be assigned.

**Comment by surajkadapa** [comment]
@IshaanNene Yes. The time limit is 1 hour. If not, others can ask to be assigned.

**Comment by surajkadapa** [comment]
This issue is closed.
