### ISSUE TITLE
Increase number of bits

### ISSUE THREAD

**Issue by surajkadapa** [surajkadapa/3_bit_up#2]
The counter only counts to 3-bits, find a way to extend it to 5 bits.

**Comment by samarth777** [comment]
yoo assign this to me

**Comment by surajkadapa** [comment]
@samarth777 Yes. The time limit is 1 hour. If not, others can ask to be assigned.

**Comment by HemaShree0408** [comment]
can i get assigned

**Comment by samarth777** [comment]
sure okay

**Comment by kavs2803** [comment]
can i be assigned please?

**Comment by euphoricair7** [comment]
Could You assign me this issue?

**Comment by IshaanNene** [comment]
Please assign me this issue

**Comment by surajkadapa** [comment]
@samarth777  you are assigned 20 more mins.

**Comment by surajkadapa** [comment]
@HemaShree0408 Yes. The time limit is 1 hour. If not, others can ask to be assigned.

**Comment by surajkadapa** [comment]
@HemaShree0408 i am reassigning it because time is out.

**Comment by surajkadapa** [comment]
@IshaanNene Yes. The time limit is 1 hour. If not, others can ask to be assigned.

**Comment by surajkadapa** [comment]
This is closed.
