### ISSUE TITLE
Reset switch

### ISSUE THREAD

**Issue by surajkadapa** [surajkadapa/3_bit_up#3]
Add a reset switch to reset at whatever point the button is pushed at.

**Comment by IshaanNene** [comment]
Can i bdemjndfs

**Comment by IshaanNene** [comment]
CAn i be assigned this

**Comment by surajkadapa** [comment]
Yes. The time limit is 1 hour. If not, others can ask to be assigned.

**Comment by PandaTGOS** [comment]
Can I get assigned to this ?

**Comment by surajkadapa** [comment]
The issue has been solved.
